### ISSUE TITLE
Maximum diameter of the flat panel...

### ISSUE THREAD

**Issue by rstjean24** [jlecomte/ascom-wireless-flat-panel#5]
Bonjour Julien, I am planing to build myself the flat panel described here. I own a Celestron 9 1/4'' SCT and I am wondering if it's possible to adapt the panel to such a diameter. I understand there no issue for at least 151 mm (your own telescope) but is the illumination for up to 235 mm feasable ?

**Comment by acocalypso** [comment]
> Bonjour Julien, I am planing to build myself the flat panel described here. I own a Celestron 9 1/4'' SCT and I am wondering if it's possible to adapt the panel to such a diameter. I understand there no issue for at least 151 mm (your own telescope) but is the illumination for up to 235 mm feasable ?

Which that diameter I don't think that a led ring can illuminate the whole area. But this is just my personal thought

**Comment by jlecomte** [comment]
The only way to find out is to try it. I think it will work.
