### ISSUE TITLE
tips for the people starting to build this

### ISSUE THREAD

**Issue by cageman1970** [jlecomte/ascom-wireless-flat-panel#7]
I struggled quite a lot to build this because i followed the instructions very precisely, and when they were not clear i followed the pictures. When these were unclear i searched online.

- At first it didnt work, even got a burning smell...
- Finally decided to turn a few things around and... everything seems to function!
The reason:

the leds
1) 'normally' the indicator for led diodes is a square marker for the positive, and a round marker for the negative (if found that online, and thats the case for the battery, led and switch connections too). But on the PCB somehow these are reversed for the led diodes and there are no indicators for the + and -. Looking back the routing drawing makes it clear (red is positive) but i'm an electrical noob...
> So: the long pin of the diode has to be inserted in the round marked hole!

The Mosfet thingy 
I just followed the pictures, so installed the Mosfet thingy with the metal back facing the Led and BAT connectors. I think that caused a bunring smell when i attached everything. And nothing worked, none of te indicator leds lit up (maybe due to the point above too). When i saw another build on youtube where they had the mosfet reversed (metal back facing the Adafruit) i  decided to give that a go. And voila!
> So the Mosfet orientation seems important too. I have no idea how to identify the right direction.

Perhaps this can be added to the instructions? Like i said i'm an absolute Noob. I just ordered the parts and decided to try it, have no clue what to do with the reamining 9994 resistors (ordered a bag full of all kinds of values). But it all is doable, just go gung-ho and start with it!

The softwarepart is the next thing i have to test, so no comments on that part for now

**Comment by jlecomte** [comment]
Thanks for the feedback. Please note that the README contains this very important tip:

> It is critical to prototype this circuit on a breadboard before ordering a PCB, or soldering the components on a perforated board.

It's unclear from your description that you attempted to prototype this project. It might have saved you a bit of time.
